services:

  frontend:
    extends:
      file: docker-compose.common.yml
      service: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${PROD_FRONTEND_PORT}:80"
    restart: always

  backend:
    extends:
      file: docker-compose.common.yml
      service: backend
    ports:
      - "${PROD_BACKEND_PORT}:8080"
    volumes:
      - caravan_uploads:/app/uploads
    restart: always


  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    extends:
      file: docker-compose.common.yml
      service: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  caravan_uploads:
  pgadmin_data:

networks:
  caravan-net:
