services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: caravan-react-dev
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./.env:/app/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    depends_on:
      - backend
    networks:
      - caravan-net

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    extends:
      file: docker-compose.common.yml
      service: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 3

  pgadmin:
    extends:
      file: docker-compose.common.yml
      service: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    #volumes:
    #  - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
  frontend_node_modules:

networks:
  caravan-net:
